#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

my $event = 'nethserver-php-scl-update';
my @templates = qw(
    /opt/remi/php56/root/etc/php.ini
    /etc/opt/remi/php70/php.ini
    /etc/opt/remi/php71/php.ini
    /etc/opt/remi/php72/php.ini
    /opt/remi/php56/root/etc/php-fpm.d/www.conf
    /etc/opt/remi/php72/php-fpm.d/www.conf
    /etc/opt/remi/php71/php-fpm.d/www.conf
    /etc/opt/remi/php70/php-fpm.d/www.conf
    );


event_actions($event,
'initialize-default-databases' => '00');

    event_templates($event, @templates);
    templates2events("/etc/httpd/conf.d/virtualhosts.conf", $event);
    templates2events("/etc/httpd/conf.d/www.conf", $event);

    event_services($event, 'httpd' => 'reload');
    event_services($event, 'php56-php-fpm' => 'restart');
    event_services($event, 'php70-php-fpm' => 'restart');
    event_services($event, 'php71-php-fpm' => 'restart');
    event_services($event, 'php72-php-fpm' => 'restart');

for my $event (qw(nethserver-php-update))
{

    event_templates($event, @templates);
    templates2events("/etc/httpd/conf.d/www.conf", $event);

    event_services($event, 'httpd' => 'reload');
    event_services($event, 'php56-php-fpm' => 'restart');
    event_services($event, 'php70-php-fpm' => 'restart');
    event_services($event, 'php71-php-fpm' => 'restart');
    event_services($event, 'php72-php-fpm' => 'restart');
}

for my $event (qw(
nethserver-php-scl-update
vhost-modify
vhost-create
vhost-delete ))
{
event_actions($event,
'nethserver-php-fpm_pool_creation' => '10');
}

for my $event (qw(
vhost-modify
vhost-create
vhost-delete ))
{
    event_services($event, 'php56-php-fpm' => 'reload');
    event_services($event, 'php70-php-fpm' => 'reload');
    event_services($event, 'php71-php-fpm' => 'restart');
    event_services($event, 'php72-php-fpm' => 'restart');
}
